//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPDataUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTPDataUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fnil\fcharset204 Lucida Console;}{\f1\fnil\fcharset0 Lucida Console;}}
        ///{\colortbl ;\red0\green100\blue0;\red0\green0\blue255;\red255\green140\blue0;\red0\green0\blue0;}
        ///\viewkind4\uc1\pard\qc\f0\fs20 ----\&apos;ca\&apos;ee\&apos;ed\&apos;f4\&apos;e8\&apos;e3\&apos;f3\&apos;f0\&apos;e0\&apos;f6\&apos;e8\&apos;ff----\par
        ///\pard ----\&apos;cd\&apos;e5\&apos;ee\&apos;e1\&apos;f5\&apos;ee\&apos;e4\&apos;e8\&apos;ec\&apos;fb\&apos;e5 \&apos;ea\&apos;ee\&apos;ec\&apos;e0\&apos;ed\&apos;e4\&apos;fb:\par
        ///\cf1 install\cf0\lang1033\f1 , \cf1\lang1049\f0 start\cf0\lang1033\f1 , \cf1\lang1049\f0 stop\cf0\lang1 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string help_1 {
            get {
                return ResourceManager.GetString("help_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fnil\fcharset204 Lucida Console;}{\f1\fnil\fcharset0 Lucida Console;}}
        ///{\colortbl ;\red0\green100\blue0;\red0\green0\blue255;\red255\green140\blue0;}
        ///\viewkind4\uc1\pard\qc\f0\fs20 ----\&apos;c2\&apos;e5\&apos;f0\&apos;f1\&apos;e8\&apos;ff----\par
        ///\pard ----\&apos;cd\&apos;e5\&apos;ee\&apos;e1\&apos;f5\&apos;ee\&apos;e4\&apos;e8\&apos;ec\&apos;fb\&apos;e5 \&apos;ea\&apos;ee\&apos;ec\&apos;e0\&apos;ed\&apos;e4\&apos;fb:\par
        ///\cf1\lang1033\f1 version\cf0 , \cf1 location\cf0 , \cf1 code\par
        ///\cf0\lang1049\f0\par
        ///---\lang1033\f1 -\lang1049\f0\&apos;c7\&apos;ed\&apos;e0\&apos;f7\&apos;e5\&apos;ed\&apos;e8\ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string help_2 {
            get {
                return ResourceManager.GetString("help_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fnil\fcharset204 Lucida Console;}{\f1\fnil\fcharset0 Lucida Console;}}
        ///{\colortbl ;\red0\green100\blue0;\red0\green0\blue255;\red255\green140\blue0;\red0\green0\blue0;}
        ///\viewkind4\uc1\pard\qc\f0\fs20 ----\&apos;ce\&apos;e1\&apos;ed\&apos;ee\&apos;e2\&apos;eb\&apos;e5\&apos;ed\&apos;e8\&apos;ff----\par
        ///\pard ----\&apos;cd\&apos;e5\&apos;ee\&apos;e1\&apos;f5\&apos;ee\&apos;e4\&apos;e8\&apos;ec\&apos;fb\&apos;e5 \&apos;ea\&apos;ee\&apos;ec\&apos;e0\&apos;ed\&apos;e4\&apos;fb:\par
        ///\cf1 type\cf0\lang1033\f1 , \cf1\lang1049\f0 date\lang1033\f1\par
        ///\cf0\lang1049\f0\par
        ///-\lang1033\f1 -\lang10 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string help_3 {
            get {
                return ResourceManager.GetString("help_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fnil\fcharset204 Lucida Console;}{\f1\fnil\fcharset0 Lucida Console;}}
        ///{\colortbl ;\red0\green100\blue0;\red0\green0\blue255;\red255\green140\blue0;\red0\green0\blue0;}
        ///\viewkind4\uc1\pard\qc\f0\fs20 ----\&apos;ca\&apos;ee\&apos;ed\&apos;f4\&apos;e8\&apos;e3\&apos;f3\&apos;f0\&apos;e0\&apos;f6\&apos;e8\&apos;ff \lang1033\f1 UIv1\lang1049\f0 ----\par
        ///\pard ----\&apos;cd\&apos;e5\&apos;ee\&apos;e1\&apos;f5\&apos;ee\&apos;e4\&apos;e8\&apos;ec\&apos;fb\&apos;e5 \&apos;ea\&apos;ee\&apos;ec\&apos;e0\&apos;ed\&apos;e4\&apos;fb:\par
        ///\cf1 config\cf0\lang1033\f1 , \cf1\lang1049\f0 log\lang1033\f1\par
        ///\cf0 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string help_4 {
            get {
                return ResourceManager.GetString("help_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fnil\fcharset204 Lucida Console;}{\f1\fnil\fcharset0 Lucida Console;}}
        ///{\colortbl ;\red255\green140\blue0;\red0\green0\blue255;\red0\green100\blue0;}
        ///\viewkind4\uc1\pard\qc\f0\fs20 ----\&apos;d1\&apos;e5\&apos;f0\&apos;e2\&apos;e5\&apos;f0\&apos;e0----\par
        ///\pard ----\&apos;c7\&apos;ed\&apos;e0\&apos;f7\&apos;e5\&apos;ed\&apos;e8\&apos;ff:\par
        ///\cf1\lang1033\f1 number\cf2 |\cf1 ip\cf2 |\cf1 username\cf2 |\cf1 password\cf0\lang1049\f0\par
        ///\par
        ///--\lang1033\f1 -\lang1049\f0 -\&apos;cf\&apos;f0\&apos;e8\&apos;ec\&apos;e5\&apos;f0:\par
        ///\cf1 1|93.188.160.18 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string help_5 {
            get {
                return ResourceManager.GetString("help_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fnil\fcharset204 Lucida Console;}{\f1\fnil\fcharset0 Lucida Console;}}
        ///{\colortbl ;\red0\green100\blue0;\red0\green0\blue255;\red255\green140\blue0;\red0\green0\blue0;}
        ///\viewkind4\uc1\pard\qc\f0\fs20 ----\&apos;cd\&apos;e0\&apos;f1\&apos;f2\&apos;f0\&apos;ee\&apos;e9\&apos;ea\&apos;e8----\par
        ///\pard ----\&apos;cd\&apos;e5\&apos;ee\&apos;e1\&apos;f5\&apos;ee\&apos;e4\&apos;e8\&apos;ec\&apos;fb\&apos;e5 \&apos;ea\&apos;ee\&apos;ec\&apos;e0\&apos;ed\&apos;e4\&apos;fb:\par
        ///\cf1 status\cf0\lang1033\f1 , \cf1\lang1049\f0 update\cf0\lang1033\f1\par
        ///\lang1049\f0\par
        ///\lang1033\f1 -\lang104 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string help_6 {
            get {
                return ResourceManager.GetString("help_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fnil\fcharset204 Lucida Console;}{\f1\fnil\fcharset0 Lucida Console;}}
        ///{\colortbl ;\red0\green100\blue0;\red0\green0\blue0;\red0\green0\blue255;\red255\green140\blue0;}
        ///\viewkind4\uc1\pard\qc\f0\fs20 ----\&apos;cd\&apos;e0\&apos;f1\&apos;f2\&apos;f0\&apos;ee\&apos;e9\&apos;ea\&apos;e8 \lang1033\f1 UI\lang1049\f0 ----\par
        ///\pard ----\&apos;cd\&apos;e5\&apos;ee\&apos;e1\&apos;f5\&apos;ee\&apos;e4\&apos;e8\&apos;ec\&apos;fb\&apos;e5 \&apos;ea\&apos;ee\&apos;ec\&apos;e0\&apos;ed\&apos;e4\&apos;fb:\par
        ///\cf1 update\cf0\lang1033\f1\par
        ///\lang1049\f0\par
        ///\lang1033\f1 -\lang1049\f0 ---\&apos;c7\ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string help_7 {
            get {
                return ResourceManager.GetString("help_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fnil\fcharset204 Lucida Console;}{\f1\fnil\fcharset0 Lucida Console;}}
        ///{\colortbl ;\red0\green0\blue255;\red0\green0\blue0;\red255\green140\blue0;}
        ///\viewkind4\uc1\pard\qc\f0\fs20 ----\&apos;ca\&apos;ee\&apos;ec\&apos;e0\&apos;ed\&apos;e4\&apos;fb----\par
        ///\pard ----\&apos;cd\&apos;e5\&apos;ee\&apos;e1\&apos;f5\&apos;ee\&apos;e4\&apos;e8\&apos;ec\&apos;fb\&apos;e5 \&apos;ee\&apos;e1\&apos;ee\&apos;e7\&apos;ed\&apos;e0\&apos;f7\&apos;e5\&apos;ed\&apos;e8\&apos;ff:\par
        ///\cf1\lang1033\f1 [always]\cf2 , \cf1 [alwayso]\cf2 , \cf1 [once]\cf2\par
        ///\cf0\lang1049\f0\par
        ///--\lang1033\f1 -\lang1049\f0 -\&apos; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string help_8 {
            get {
                return ResourceManager.GetString("help_8", resourceCulture);
            }
        }
    }
}
